name: scroll_date_picker
description: A customizable and easy-to-use date picker library for Flutter. Compatible with Android & iOS & Web.
version: 3.7.4
homepage: https://github.com/mincheol-shin/scroll_date_picker

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


platforms:
  android:
  ios:
